results_dir: /home/scratch.p3/sean/groundingdino/tao_integration/
dataset:
  test_data_sources:
    image_dir: /home/scratch.p3/sean/datasets/coco/raw-data/val2017/
    json_file: /home/scratch.p3/sean/datasets/coco/raw-data/annotations/instances_val2017_remapped.json
  batch_size: 4
  workers: 8
evaluate:
  trt_engine: /home/scratch.p3/sean/groundingdino/tao_integration/swint2.engine
  input_width: 960
  input_height: 544
model:
  backbone: swin_tiny_224_1k
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 900
  dropout_ratio: 0.0
  dim_feedforward: 2048