results_dir: "???"
dataset:
  test_data_sources:
    image_dir: "???"
    json_file: "???"
  batch_size: 1
  workers: 8
evaluate:
  trt_engine: "???"
  input_width: 960
  input_height: 544
  conf_threshold: 0.5
model:
  backbone: swin_tiny_224_1k
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 900
  dropout_ratio: 0.0
  dim_feedforward: 2048