encryption_key: "???"
results_dir: "???"
dataset:
  test_data_sources:
    image_dir: "???"
    json_file: "???"
  num_classes: 4
  batch_size: 10
  workers: 8
  eval_class_ids: [1]
model:
  num_feature_levels: 2
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  with_box_refine: True
evaluate:
  trt_engine: "???"
  conf_threshold: 0.0
  input_width: 960
  input_height: 544
