encryption_key: "???"
results_dir: "???"
dataset:
  infer_data_sources:
    image_dir: 
      - "???"
    classmap: "???"
  num_classes: 4
  batch_size: 8
  workers: 8
inference:
  trt_engine: "???"
  conf_threshold: 0.5
  input_width: 960
  input_height: 544
  color_map:
    person: green
model:
  num_feature_levels: 2
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  with_box_refine: True